### ISSUE TITLE
bug: 키보드 제어를 위한 예시에서, 스크롤이 동시에 일어납니다

### ISSUE THREAD

**Issue by cog25** [rycont/stadium#3]
https://github.com/rycont/stadium/blob/b59296baf99f337ab9f944276e81626ddbd92429/docs/index.md?plain=1#L12-L55
해당 부분에서 발생하는 오류로, 상세한 내용은 다음과 같습니다.

https://youtu.be/ddxvYWXLbNM
예시를 확인해보기 위해 방향키만을 눌렀습니다!

p.s. 영상 원본 화질을 잘못 설정했네요.... ㅜ

**Comment by rycont** [comment]
It's an intended behavior! 방향키로 문서를 탐색하시는 분들이 많을거라고 생각해서 일부러 스크롤 동작을 막지 않았습니다.

**Comment by cog25** [comment]
으앙😅

혹시 방향키 대신 `wasd`로 하는 방향도 고려해 보셨을까요..?
